### ISSUE TITLE
Template not uploading

### ISSUE THREAD

**Issue by miheins** [chrisvxd/og-impact#26]
Hi,
It looks like the template we are saving is not uploading to the URL but it always falls back to the default background image and watermark. Are there any obvious mistakes that could prevent the propagation that I am not aware of?

**Comment by garryreeve** [comment]
Experiencing a similar issue. Publish successful, getting new template ID but still seeing the default template when referencing the new template.

**Comment by chrisvxd** [comment]
Hi both! Would you be able to share the URLs you're trying to call?

**Comment by miheins** [comment]
Sure! I am trying to get to https://ogi.sh/?template=QeD2WGmM9 but it only renders the default template.
I have also made https://ogi.sh/?template=RTTmJanQg which is the example template but with a red background, and am not getting anything out of it either.

**Comment by chrisvxd** [comment]
Hi Miheins! Try this: https://ogi.sh/QeD2WGmM9

Looks like the docs are a little of date. I'll get that fixed asap.

**Comment by chrisvxd** [comment]
So I've double checked my thinking, and either of the above URL formats should work. I've patched the ogi.sh proxy to fix, and will also update docs as preferred approach is the shorthand I referenced. Thanks for bringing this to my attention.

@garryreeve Let me know if this has helped you, too.

Will close issue once you've both confirm it's working.

**Comment by miheins** [comment]
Thanks so much @chrisvxd that is working now as expected! Appreciate you looking into this for me so swiftly.

**Comment by chrisvxd** [comment]
No problem! I'm closing this now.

@garryreeve if you're still having an issue, please feel free to open a new ticket.
