### ISSUE TITLE
Support instagram sizing

### ISSUE THREAD

**Issue by chrisvxd** [chrisvxd/og-impact#9]
Although it won't be usable by a `meta` tag, OG IMPACT should support instagram images for cases where people wish to share the image by other means.

**Comment by sharegrams** [comment]
og-impact is SAAS for the well defined use-case of meta tag support and advertising their service, which I think is cool and valuable for people without much technical experience. 

For those that have technical experience and want something custom, you could make your own images with variables using [imagemagick](https://imagemagick.org/script/download.php) and [resize scripting](http://www.imagemagick.org/Usage/resize/). Although this maybe advanced, I have made a lot of interesting media with imagemagick. If you put in the time to learn it, it will be very rewarding.

**Comment by chrisvxd** [comment]
Closed in 0e4149c
